openapi: 3.1.0 

info: 

  title: Syracuse Code Violations API 

  description: API for accessing code violations data and listing available features. 

  version: 1.0.0 

servers: 

  - url: https://services6.arcgis.com/bdPqSfflsdgFRVVM/arcgis/rest/services/Code_Violations_v2/FeatureServer/0 

paths: 

  /query: 

    get: 

      summary: Get Code Violations Data 

      description: Retrieves code violations data based on query parameters. 

      operationId: getCodeViolations 

      parameters: 

        - in: query 

          name: where 

          schema: 

            type: string 

          description: SQL-like WHERE clause to filter results.  For dates, use datetime format 

        - in: query 

          name: outFields 

          schema: 

            type: string 

          description: Comma-separated list of fields to include in the output.  Should default to "violation_number,complaint_address,violation_date,status_type_name,owner_name,complaint_zip,complaint_type_name"

        - in: query 

          name: returnGeometry 

          schema: 

            type: boolean 

          description: Whether to include geometry data in the output. 

        - in: query 

          name: f 

          schema: 

            type: string 

            enum: [json, pjson, geojson] 

          description: Format of the response. 

        - in: query 

          name: outSR 

          schema: 

            type: string 

          description: Spatial reference of the output geometries. 

      responses: 

        '200': 

          description: Successful response 

          content: 

            application/json: 

              schema: 

                type: object 

                properties: 

                  features: 

                    type: array 

                    items: 

                      type: object 

                      properties: 

                        attributes: 

                          type: object 

                          additionalProperties: 

                            type: string 

                        geometry: 

                          type: object 

                          properties: 

                            x: 

                              type: number 

                            y: 

                              type: number 